#!/usr/bin/env python3
"""Builds docs/traceability.md from docs/requirements.md and the @Verifies annotations in the tests.

  scripts/traceability.py           regenerate docs/traceability.md
  scripts/traceability.py --check   also fail if a requirement that is not manual-only has no test,
                                    or if docs/traceability.md is out of date
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "docs" / "requirements.md"
OUTPUT = ROOT / "docs" / "traceability.md"

ROW = re.compile(r"^\|\s*(SR-\d+)\s*\|(.+?)\|(.+?)\|(.+?)\|\s*$")
VERIFIES = re.compile(r"@Verifies\(([^)]*)\)")
FUNCTION = re.compile(r"fun\s+`([^`]+)`|fun\s+(\w+)\s*\(")
CLASS = re.compile(r"^\s*(?:internal\s+)?class\s+(\w+)")


def requirements():
    reqs = []
    for line in REQUIREMENTS.read_text().splitlines():
        m = ROW.match(line)
        if m:
            reqs.append((m[1], m[2].strip(), m[4].strip()))
    return reqs


def verifying_tests():
    """Maps requirement ID -> list of "path: Class > test name"."""
    found = {}
    for path in sorted(ROOT.glob("*/src/test/**/*.kt")) + sorted(ROOT.glob("*/*/src/test/**/*.kt")):
        lines = path.read_text().splitlines()
        cls = None
        for i, line in enumerate(lines):
            c = CLASS.match(line)
            if c:
                cls = c[1]
            m = VERIFIES.search(line)
            if not m:
                continue
            ids = re.findall(r'"([^"]+)"', m[1])
            # The annotated element is the next class or function declaration.
            target = None
            for nxt in lines[i + 1 : i + 6]:
                f = FUNCTION.search(nxt)
                k = CLASS.match(nxt)
                if f:
                    target = f[1] or f[2]
                    break
                if k:
                    target = f"{k[1]} (all tests)"
                    break
            label = f"`{path.relative_to(ROOT)}`: {cls or '?'} > {target or '?'}"
            for rid in ids:
                found.setdefault(rid, []).append(label)
    return found


def render(reqs, tests):
    out = [
        "# Traceability",
        "",
        "Generated by `scripts/traceability.py` from [requirements.md](requirements.md) and the",
        "`@Verifies` annotations in the tests. Do not edit by hand.",
        "",
        "| Requirement | Verification | Tests |",
        "|---|---|---|",
    ]
    for rid, _text, how in reqs:
        names = tests.get(rid, [])
        cell = "<br>".join(names) if names else "**none**"
        out.append(f"| {rid} | {how} | {len(names)}: {cell} |")
    scenarios = sorted((k for k in tests if k.startswith("U")), key=lambda s: int(s[1:]))
    if scenarios:
        out += ["", "## User scenarios", "", "| Scenario | Tests |", "|---|---|"]
        for sid in scenarios:
            out.append(f"| {sid} | {len(tests[sid])}: " + "<br>".join(tests[sid]) + " |")
    return "\n".join(out) + "\n"


def main():
    reqs = requirements()
    tests = verifying_tests()
    text = render(reqs, tests)
    check = "--check" in sys.argv
    problems = []
    for rid, _text, how in reqs:
        # Requirements verified only by the manual test plan or by a build check have no @Verifies test.
        manual_only = ("manual" in how.lower() or "build check" in how.lower()) and "unit" not in how.lower()
        if not manual_only and not tests.get(rid):
            problems.append(f"{rid} has no verifying test (verification: {how})")
    unknown = sorted(k for k in tests if k.startswith("SR-") and k not in {r[0] for r in reqs})
    problems += [f"{k} is referenced by a test but not listed in requirements.md" for k in unknown]
    if check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            problems.append("docs/traceability.md is out of date; run scripts/traceability.py")
    else:
        OUTPUT.write_text(text)
    for p in problems:
        print("error:", p, file=sys.stderr)
    if problems:
        sys.exit(1)
    print(f"{len(reqs)} requirements, {sum(1 for r in reqs if tests.get(r[0]))} with tests")


if __name__ == "__main__":
    main()
